# Generated by Django 5.2.3 on 2025-07-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0002_user_callback_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
