# Generated by Django 5.2.3 on 2025-07-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0003_callback_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='callback',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
