# Generated by Django 5.2.3 on 2025-07-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0006_user'),
    ]

    operations = [
    ]
