# Generated by Django 5.2.3 on 2025-07-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0007_auto_20250703_0859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
