# Generated by Django 5.2.3 on 2025-07-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0009_alter_callback_options_callback_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='priority',
        ),
    ]
