# Generated by Django 5.2.3 on 2025-07-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0010_remove_callback_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callback',
            options={'permissions': [('view_all_callbacks', 'Can view all callbacks'), ('edit_all_callbacks', 'Can edit all callbacks'), ('delete_all_callbacks', 'Can delete all callbacks'), ('manage_users', 'Can manage users')]},
        ),
    ]
