# Generated by Django 5.2.3 on 2025-07-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0014_remove_callback_details_callback_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='device_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
