# Generated by Django 5.2.3 on 2025-07-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0015_callback_device_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='device_info',
        ),
    ]
