# Generated by Django 5.2.3 on 2025-07-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0016_remove_callback_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
