# Generated by Django 5.2.3 on 2025-07-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0017_callback_added_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callback',
            options={'permissions': [('view_all_callbacks', 'Can view all callbacks'), ('edit_all_callbacks', 'Can edit all callbacks'), ('delete_all_callbacks', 'Can delete all callbacks'), ('manage_users', 'Can manage users'), ('manage_managers', 'Can manage managers')]},
        ),
    ]
