# Generated by Django 5.2.3 on 2025-07-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0018_alter_callback_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
