# Generated by Django 5.2.3 on 2025-07-13 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0019_callback_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_callbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='callback',
            index=models.Index(fields=['manager'], name='callbacks_c_manager_4a4818_idx'),
        ),
    ]
